$ANSIBLE_VAULT;1.1;AES256
62383333666337616263643734666435356264666365666430333939626561653537363935363564
6463653830643732303361353731336133366166623434610a386238343036363665376531326361
33326136353335393731396637393066353635653036326636636264616262646632386239666630
6265643536346263650a393064333135353237313536313132343765356133373162393138316231
35386537373766383966396365626531376232616466646637323635346366383939386631343365
33626561306364333836396566613736653232366431613938623833316538393564636331326535
65326432383733623435393431666261396438346630663936336137623336363639376166653635
30633765633634646233653934373433653531656562353461303339633033306631343438303031
66663131646336343566323463353532643030353933313164343932623839353631343432633061
3135343234633664326438333738643033313433653038333439
